### ISSUE TITLE
ERROR Line 165 and 171

### ISSUE THREAD

**Issue by Kristories** [remoharsono/remoFramework#1]
I've been encountering an issue whereby any fatal errors that occur during execution are not displayed to the browser.

I'm using Windows (WAMPSERVER and AMPPS). I tried tracing the problem and I found error (README - ERROR Line 165 and 171), but it have only one line -_- 

I recommend someone with more experience of README (markdown) and the remoFramework core code looks at this issue because I've got to the end of my talents in so far as identifying this issue.

**Comment by fianlab** [comment]
if you see blank page on your browser that mean you have successfully install and running this framework

**Comment by zlumber** [comment]
you should try RemoFramework
